### ISSUE TITLE
Create "Tournament summary"

### ISSUE THREAD

**Issue by ppadamczyk** [cysi4k/battle-board-spa#16]
Design and create Tournament Summary page based on the model specified here:
https://docs.google.com/document/d/1s8BkYMv2YpACiB8XhTT7UXUOdc9SeBklmn2Eh9z_mrc/edit?fbclid=IwAR2mlsL0_lVSFSIR_EMwIFd1Rr3cToiF4_m70kwlVqNht7veQI5ZIY6sxoQ

**Comment by cysi4k** [comment]
Tournament summary ----> Tournament details
Page access through page with list of user tournaments
