### ISSUE TITLE
Research prototype tools

### ISSUE THREAD

**Issue by cysi4k** [cysi4k/battle-board-spa#2]
Do a research on available free tools for making prototypes. Prototype has to be interactive and available online. Example tools:

- Rise (30 days free trial)
- Mockplus (free)
- Antetype (30 days free trial)
- Justinmind (30 days free trial)
- UXPin (7-30 day ft)
- Invision (1 project for free)
- POP (2 projects for free)
- Marvel (free if no coop)
- Balsamiq (30 days ft)
- Axure (free version for students, 30 days ft)
- Flinto (30)
- Proto.io (15)
- Moqups (free)
- Pencil Project (free, desktop + FF web plugin)
- Pidoco (31)
- Creately (free account and online version)
- HotGloo (free, online)

Choose the one you think is best.

**Comment by duudey** [comment]
In my opinion best tool from list above is hotgloo.
Adventages:
+ online
+ free
+ easy to share with others
+ easy to understand
+ fun to work with
Disadventages:
- project of app is not responsive
- only one person can work with it
